### ISSUE TITLE
Add more + project status

### ISSUE THREAD

**Issue by hongkongkiwi** [rustyshackleford36/locatarr#1]
Please list the status of the project.... some e.g. Bonarr, Darkarr are dead.

Here's two more for your list:
* Traktarr
* Syncarr
* NZBHydra2
* plextraktsync
* ombi
* ldap-plex
* lazylibrarian
* gaps

**Comment by rustyshackleford36** [comment]
Thanks for the heads up! I need to dedicate more time to this to really wrap it up. I should be able to knock some of this out tomorrow! 

Off the top of your head, do you know of any way to pull in GitHub data to show if it’s active or still maintained etc?? Similar to the download counts I have on some of them.

**Comment by rustyshackleford36** [comment]
@hongkongkiwi Take a look whenever you get a chance -- I am not sure how I feel about the repo badges (for downloads) at least. 

I still have more to add, but let me know your thoughts.

**Comment by rustyshackleford36** [comment]
Doing a major rewrite of the table, will include these!

**Comment by rustyshackleford36** [comment]
Closing this for now as we completed a massive update and rewrite. Feel free to open up an issue to add a service you don't see.
