### ISSUE TITLE
Commandarr abandoned

### ISSUE THREAD

**Issue by Tragyn** [rustyshackleford36/locatarr#3]
Commandarr hasn't had a commit in over four years, and was pre-alpha to start. Should be removed until a time it is updated.

**Comment by rustyshackleford36** [comment]
I'm interested to hear what others think to. On one hand I agree because it's likely to not function properly. On the other hand I wonder if someone would find it here and update it.

**Comment by rustyshackleford36** [comment]
Going to leave it just in case someone comes across it via this page and decides to update it.
