### ISSUE TITLE
Excludarr Elsewherr radarr-striptracks mp4_automator Reciperr mdblists radarr_autodelete

### ISSUE THREAD

**Issue by neo-neo1** [rustyshackleford36/locatarr#30]
https://github.com/Adman1020/Elsewherr

https://github.com/haijeploeg/excludarr

https://github.com/linuxserver/docker-mods/tree/radarr-striptracks

https://github.com/mdhiggins/sickbeard_mp4_automator

https://reciperr.ml/

https://mdblist.com/

https://github.com/JCSynthTux/radarr_autodelete

**Comment by rustyshackleford36** [comment]
Done
