### ISSUE TITLE
Background info 

### ISSUE THREAD

**Issue by glensc** [rustyshackleford36/locatarr#5]
Could you find and add some background story of them. Why they are named like this?

And why most of them are written in dotnet and forks of each other rather adding the other support to the same codebase. Seems a lot of duplication to have radarr/sonarr in different codebase.

**Comment by rustyshackleford36** [comment]
Sonarr was the first, and most of them (Radarr, Lidarr for sure) are based on them. The reason they're "Arr" is because that's what a pirate says.

**Comment by glensc** [comment]
Can that reason be added to readme then? why close without adding it?
