### ISSUE TITLE
Add Monitorr and Logarr

### ISSUE THREAD

**Issue by BobDaGecko** [rustyshackleford36/locatarr#6]
This is super great, here are a couple more to add.

| Service                                                                         | Usage                                                          | Recent Activity                                                                                         | Github                                                    | Reddit |
| ------------------------------------------------------------------------------- | -------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- | --------------------------------------------------------- | ------ |
| Monitorr ![Docker Pulls](https://img.shields.io/docker/pulls/monitorr/monitorr) | A webfront to live display the status of any webapp or service | ![GitHub last commit](https://img.shields.io/github/last-commit/Monitorr/Monitorr?label=last%20updated) | [Monitorr/Monitorr](https://github.com/Monitorr/Monitorr) |        |
| Logarr ![Docker Pulls](https://img.shields.io/docker/pulls/monitorr/logarr)     | A log consolidation tool written in PHP                        | ![GitHub last commit](https://img.shields.io/github/last-commit/Monitorr/logarr?label=last%20updated)   | [Monitorr/logarr](https://github.com/Monitorr/logarr)     |

**Comment by rustyshackleford36** [comment]
Thanks for this! I'm a little new to Github, so I am not entirely sure how I can pull your markdown out of thatr comment. Is it possible for you to do a pull request and add them? Or you can tell me how to do it, so I don't have to recreate your work ;)

**Comment by rustyshackleford36** [comment]
Fixed. Added.
