### ISSUE TITLE
Darkerr

### ISSUE THREAD

**Issue by GilbN** [rustyshackleford36/locatarr#9]
Since Darkerr is no longer being developed on, I thought I could let you know a project I started a litte while ago :)

https://github.com/gilbN/theme.park
It has themes for all the "arrs"

**Comment by rustyshackleford36** [comment]
Thanks! I will add it next time I'm able to update it (or you can pull and do it, feel free!).

**Comment by gilbN** [comment]
Made a pr btw https://github.com/rustyshackleford36/locatarr/pull/14
